#!/usr/bin/env python3
"""fcode2vhd.py TCX.bin CG3.bin > rtl/sun4m/ts_fcode_pack.vhd

Turn the display FCode images into the VHDL package ts_tcx serves at the
frame buffer's SBus slot base (offset 0), where a Sun OBP probes for a
card's FCode.

The images are QEMU's pc-bios/QEMU,tcx.bin and QEMU,cgthree.bin, built from
the OpenBIOS FCode sources (GPL-2; QEMU pc-bios/README: "built from
OpenBIOS SVN revision 1280"). They describe the same 1024x768x8 TCX and the
CG3 that the core implements; the TACUS OpenBIOS carries its own copy of the
same drivers and never probes the slot, so this only matters to the Sun OBP.
"""
import sys

WORDS = 512                     # 2 KiB per image


def words(path):
    data = open(path, 'rb').read()
    if len(data) > WORDS * 4:
        sys.exit(f'{path}: {len(data)} bytes, more than {WORDS * 4}')
    data += b'\xff' * (WORDS * 4 - len(data))
    return [int.from_bytes(data[i:i + 4], 'big') for i in range(0, len(data), 4)], len(data)


def const(name, path):
    w, _ = words(path)
    size = len(open(path, 'rb').read())
    lines = [f'  -- {path.split("/")[-1]}, {size} bytes']
    lines.append(f'  CONSTANT {name} : arr_fcode := (')
    for i in range(0, WORDS, 6):
        chunk = ', '.join(f'x"{v:08X}"' for v in w[i:i + 6])
        sep = ',' if i + 6 < WORDS else ');'
        lines.append(f'    {chunk}{sep}')
    return '\n'.join(lines)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    print(f'''--------------------------------------------------------------------------------
-- Display FCode for the frame buffer's SBus slot (offset 0), read by a Sun OBP
-- probing the slot. Generated by tools/fcode2vhd.py; do not edit.
--
-- Source: QEMU pc-bios/QEMU,tcx.bin and QEMU,cgthree.bin, built from the
-- OpenBIOS FCode sources (GPL-2), QEMU 11.1.1.
--------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

LIBRARY work;
USE work.base_pack.ALL;

PACKAGE ts_fcode_pack IS
  -- 32-bit big-endian words: byte n of the image is in word n/4, lane n mod 4
  TYPE arr_fcode IS ARRAY(0 TO {WORDS - 1}) OF uv32;

{const('FCODE_TCX', sys.argv[1])}

{const('FCODE_CG3', sys.argv[2])}
END PACKAGE ts_fcode_pack;''')


if __name__ == '__main__':
    main()
